### ISSUE TITLE
Export functionality

### ISSUE THREAD

**Issue by Dave-stat** [stla/rAmCharts4#2]
Hi - Just wanted to check if exporting functionality (export data to Excel, Image ) is available in this awesome charting library.

**Comment by stla** [comment]
Hello @Dave-stat 

 The export to image is available: option `export = TRUE`. I have not included the export to Excel because we can do it in R, and I don't see the interest in including it in the chart.

**Comment by markwsac** [comment]
Thanks for this useful package. Export underlying data of graph to Excel is an important feature most of the stakeholders demand. Currently I am using highcharter and this feature is available in the library. Would love to migrate to rAmCharts4 if this feature is available as this is one of the main functionality we have in running apps.

**Comment by stla** [comment]
@markwsac The data of the graph is the one you supply. So what is the interest in exporting it? I may miss something.

**Comment by markwsac** [comment]
Thanks. I mean our shiny app allows users to download graph in png format along with the underlying data of graph if user wants to see it in excel. I understand we can have a separate download button for the same but it's a bit cumbersome to write code for export to excel functionality for each graph (6 graphs in one page). Also it's elegant to show icon at the top right of graph which opens menu to export in png or excel format
